name: Build and Upload Java Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Replace with your project's Java version
          distribution: 'temurin'

      # Step 3: Build the project (Maven or Gradle)
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-artifact
          path: target/*.jar # Adjust the path based on your JAR/WAR output
